version: '2'
services:
  mysql:
    image: percona:8.0.23-14
    ports:
       - 3306:3306
  
  app_server1:
    image: nginx
    ports:
       - 8081:80
    volumes:
       - ./src:/usr/share/nginx/html
    links:
       - mysql:mysql
    depends_on:
       - mysql

  app_server2:
    image: nginx
    ports:
       - 8082:80
    volumes:
       - ./src:/usr/share/nginx/html
    links:
       - mysql:mysql
    depends_on:
       - mysql
 
  nginx:
    image: nginx
    ports:
       - 8080:80
    depends_on:
       - mysql
       - app_server1
       - app_server2  
